app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Dynatrace

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

techdocs:
  builder: local

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]
  locations:
    - type: file
      target: ../../catalog-info.yaml

dynatrace:
  queries:
    - id: davis-events
      description: Fetches all Davis events
      query: >
        fetch events | filter event.kind == "DAVIS_EVENT" | fields event.kind, timestamp
