name: "Collect metadata"

description: "Retrieves metadata and makes it available as environment variables and outputs."

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      run: |
        echo "Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
      shell: bash

outputs:
  isRelease:
    description: "Is this a release build?"
    value: ${{ startsWith(github.ref, 'refs/tags/v') && 'true' || '' }}
  isDefaultOrReleaseBranch:
    description: "Is this the default branch or a release branch?"
    value: ${{ (github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/heads/release/')) && 'true' || '' }}
  isTargetBranchDefaultOrReleaseBranch:
    description: "Is the target branch the default branch or a release branch?"
    value: ${{ (github.base_ref == github.event.repository.default_branch || startsWith(github.base_ref, 'release/')) && 'true' || '' }}
