name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'x.x.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint:all

      - name: Compile TypeScript
        run: yarn tsc:full

      - name: Build
        run: yarn build:all

      - name: Run Tests
        run: yarn test:all

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc

      - name: Publish to GitHub Package Registry
        run: npx lerna publish ${{ github.event.inputs.version }} --yes --no-git-tag-version --no-push --force-publish --registry https://npm.pkg.github.com
